# MARKET BASKET ANALYSIS

In [1]:
import sys
sys.executable

'd:\\YOM\\Project\\YOM-Recommender-System\\venv\\Scripts\\python.exe'

In [2]:
import polars as pl
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# import seaborn as sns
import glob

In [3]:
import polars as pl
from pymongo import MongoClient

In [4]:
# 1. Подключение к MongoDB
MONGO_URI = "mongodb+srv://dianakhutorna_db_user:1MkZZDOie0bztsUk@yom.adk31s4.mongodb.net/?appName=YOM"
client = MongoClient(MONGO_URI)
db = client["mydatabase"]
collection = db["results"]

In [5]:
# 2. Подсчет корзин из большого CSV с ленивой обработкой (стриминг)
baskets_lf = (
    pl.scan_csv("../data/2024-20250001_part_00-001.csv", has_header=True)
    .select(["orderid", "productid"])
    .group_by("orderid")
    .agg(pl.col("productid").unique().alias("products"))
)

In [6]:
# 3. Сохраняем корзины в файл (или collect напрямую)
baskets_df = baskets_lf.collect(streaming=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_10856\3860485890.py:2: DeprecationWarning: the `streaming` parameter was deprecated in 1.25.0; use `engine` instead.
  baskets_df = baskets_lf.collect(streaming=True)

In [ ]:
# 4. Получаем пары товаров в одном заказе
import itertools

# получаем пары прямо внутри каждой корзины (в Python)
def basket_to_pairs(row):
    products = row["products"]
    return list(itertools.combinations(sorted(set(products)), 2))

pairs_df = (
    baskets_df
    .with_columns([
        pl.struct(["orderid", "products"]).map_elements(basket_to_pairs).alias("pairs")
    ])
    .explode("pairs")
    .drop_nulls()
    .with_columns([
        pl.col("pairs").arr.get(0).alias("item_A"),
        pl.col("pairs").arr.get(1).alias("item_B")
    ])
    .group_by(["item_A", "item_B"])
    .count()
    .rename({"count": "pair_count"})
)

In [ ]:
# 5. Подсчет частот каждого товара
item_freq = (
baskets_df.explode("products")
.group_by("products")
.count()
.rename({"products": "item", "count": "item_count"})
)


# 6. Расчет support, confidence, lift
total_orders = baskets_df.height
rules = (
pairs
.join(item_freq.rename({"item": "item_A", "item_count": "count_A"}), on="item_A")
.join(item_freq.rename({"item": "item_B", "item_count": "count_B"}), on="item_B")
.with_columns([
(pl.col("pair_count") / total_orders).alias("support"),
(pl.col("pair_count") / pl.col("count_A")).alias("confidence"),
((pl.col("pair_count") * total_orders) / (pl.col("count_A") * pl.col("count_B"))).alias("lift")
])
)


# 7. Топ-правила с высоким lift
top_rules = (
rules.filter(pl.col("lift") > 1.5)
.sort("lift", descending=True)
.head(20)
)


# 8. Сохраняем топ-правила в MongoDB
for row in top_rules.iter_rows(named=True):
doc = {
"item_A": row["item_A"],
"item_B": row["item_B"],
"support": float(row["support"]),
"confidence": float(row["confidence"]),
"lift": float(row["lift"])
}
collection.insert_one(doc)


print("Завершено: правила сохранены в MongoDB")

# code is working

In [1]:
# Market Basket Analysis with Polars + Batch Processing (RAM-Safe)

import polars as pl
import itertools
from collections import Counter, defaultdict
import math
import os

In [2]:
# Путь к файлу CSV (относительно папки notebooks)
DATA_PATH = "../data/2024-20250001_part_00-001.csv"
BATCH_SIZE = 10_000

# Список путей ко всем CSV-файлам
DATA_FILES = [
    #"../data/2024-20250001_part_00-001.csv",
    "../data/2024-20250000_part_00-003.csv",
    #"../data/2022-20230000_part_00-002.csv",
    "../data/2022-20230001_part_00-004.csv"
]

import glob

# Получаем список всех CSV-файлов в папке ../data
# DATA_FILES = sorted(glob.glob("../data/*.csv"))

# Словарь для хранения количества каждой пары товаров
pair_counter = Counter()
item_counter = Counter()
total_orders = 0  # суммарно по всем файлам

In [9]:
# 1. Получаем общее количество заказов
order_ids = pl.read_csv(DATA_PATH, columns=["orderid"]).unique()
total_orders = order_ids.height

In [ ]:
# 2. Читаем файл чанками по заказам - 6 минут
for i in range(0, total_orders, BATCH_SIZE):
    batch_ids = order_ids.slice(i, BATCH_SIZE)


    batch_df = (
        pl.read_csv(DATA_PATH, columns=["orderid", "productid"])
        .join(batch_ids, on="orderid", how="inner")
        .group_by("orderid")
        .agg(pl.col("productid").unique().alias("products"))
    )


    for row in batch_df.iter_rows(named=True):
        products = sorted(set(row["products"]))
        item_counter.update(products)
        pairs = itertools.combinations(products, 2)
        pair_counter.update(pairs)


    print(f"Обработано заказов: {min(i + BATCH_SIZE, total_orders)} / {total_orders}")

Обработано заказов: 10000 / 1485720
Обработано заказов: 20000 / 1485720
Обработано заказов: 30000 / 1485720
Обработано заказов: 40000 / 1485720
Обработано заказов: 50000 / 1485720
Обработано заказов: 60000 / 1485720
Обработано заказов: 70000 / 1485720
Обработано заказов: 80000 / 1485720
Обработано заказов: 90000 / 1485720
Обработано заказов: 100000 / 1485720
Обработано заказов: 110000 / 1485720
Обработано заказов: 120000 / 1485720
Обработано заказов: 130000 / 1485720
Обработано заказов: 140000 / 1485720
Обработано заказов: 150000 / 1485720
Обработано заказов: 160000 / 1485720
Обработано заказов: 170000 / 1485720
Обработано заказов: 180000 / 1485720
Обработано заказов: 190000 / 1485720
Обработано заказов: 200000 / 1485720
Обработано заказов: 210000 / 1485720
Обработано заказов: 220000 / 1485720
Обработано заказов: 230000 / 1485720
Обработано заказов: 240000 / 1485720
Обработано заказов: 250000 / 1485720
Обработано заказов: 260000 / 1485720
Обработано заказов: 270000 / 1485720
Обработано заказов: 280000 / 1485720
Обработано заказов: 290000 / 1485720
Обработано заказов: 300000 / 1485720
Обработано заказов: 310000 / 1485720
Обработано заказов: 320000 / 1485720
Обработано заказов: 330000 / 1485720
Обработано заказов: 340000 / 1485720
Обработано заказов: 350000 / 1485720
Обработано заказов: 360000 / 1485720
Обработано заказов: 370000 / 1485720
Обработано заказов: 380000 / 1485720
Обработано заказов: 390000 / 1485720
Обработано заказов: 400000 / 1485720
Обработано заказов: 410000 / 1485720
Обработано заказов: 420000 / 1485720
Обработано заказов: 430000 / 1485720
Обработано заказов: 440000 / 1485720
Обработано заказов: 450000 / 1485720
Обработано заказов: 460000 / 1485720
Обработано заказов: 470000 / 1485720
Обработано заказов: 480000 / 1485720
Обработано заказов: 490000 / 1485720
Обработано заказов: 500000 / 1485720
Обработано заказов: 510000 / 1485720
Обработано заказов: 520000 / 1485720
Обработано заказов: 530000 / 1485720
Обработано заказов: 540000 / 1485720
Обработано заказов: 550000 / 1485720
Обработано заказов: 560000 / 1485720
Обработано заказов: 570000 / 1485720
Обработано заказов: 580000 / 1485720
Обработано заказов: 590000 / 1485720
Обработано заказов: 600000 / 1485720
Обработано заказов: 610000 / 1485720
Обработано заказов: 620000 / 1485720
Обработано заказов: 630000 / 1485720
Обработано заказов: 640000 / 1485720
Обработано заказов: 650000 / 1485720
Обработано заказов: 660000 / 1485720
Обработано заказов: 670000 / 1485720
Обработано заказов: 680000 / 1485720
Обработано заказов: 690000 / 1485720
Обработано заказов: 700000 / 1485720
Обработано заказов: 710000 / 1485720
Обработано заказов: 720000 / 1485720
Обработано заказов: 730000 / 1485720
Обработано заказов: 740000 / 1485720
Обработано заказов: 750000 / 1485720
Обработано заказов: 760000 / 1485720
Обработано заказов: 770000 / 1485720
Обработано заказов: 780000 / 1485720
Обработано заказов: 790000 / 1485720
Обработано заказов: 800000 / 1485720
Обработано заказов: 810000 / 1485720
Обработано заказов: 820000 / 1485720
Обработано заказов: 830000 / 1485720
Обработано заказов: 840000 / 1485720
Обработано заказов: 850000 / 1485720
Обработано заказов: 860000 / 1485720
Обработано заказов: 870000 / 1485720
Обработано заказов: 880000 / 1485720
Обработано заказов: 890000 / 1485720
Обработано заказов: 900000 / 1485720
Обработано заказов: 910000 / 1485720
Обработано заказов: 920000 / 1485720
Обработано заказов: 930000 / 1485720
Обработано заказов: 940000 / 1485720
Обработано заказов: 950000 / 1485720
Обработано заказов: 960000 / 1485720
Обработано заказов: 970000 / 1485720
Обработано заказов: 980000 / 1485720
Обработано заказов: 990000 / 1485720
Обработано заказов: 1000000 / 1485720
Обработано заказов: 1010000 / 1485720
Обработано заказов: 1020000 / 1485720
Обработано заказов: 1030000 / 1485720
Обработано заказов: 1040000 / 1485720
Обработано заказов: 1050000 / 1485720
Обработано заказов: 1060000 / 1485720
Обработано заказов: 1070000 / 1485720
Обработано заказов: 1080000 / 1485720
Обработано заказов: 1090000 / 1485720
Обработано заказов: 1100000 / 1485720
Обработано заказов: 1110000 / 1485720
Обработано заказов: 1120000 / 1485720
Обработано заказов: 1130000 / 1485720
Обработано заказов: 1140000 / 1485720
Обработано заказов: 1150000 / 1485720
Обработано заказов: 1160000 / 1485720
Обработано заказов: 1170000 / 1485720
Обработано заказов: 1180000 / 1485720
Обработано заказов: 1190000 / 1485720
Обработано заказов: 1200000 / 1485720
Обработано заказов: 1210000 / 1485720
Обработано заказов: 1220000 / 1485720
Обработано заказов: 1230000 / 1485720
Обработано заказов: 1240000 / 1485720
Обработано заказов: 1250000 / 1485720
Обработано заказов: 1260000 / 1485720
Обработано заказов: 1270000 / 1485720
Обработано заказов: 1280000 / 1485720
Обработано заказов: 1290000 / 1485720
Обработано заказов: 1300000 / 1485720
Обработано заказов: 1310000 / 1485720
Обработано заказов: 1320000 / 1485720
Обработано заказов: 1330000 / 1485720
Обработано заказов: 1340000 / 1485720
Обработано заказов: 1350000 / 1485720
Обработано заказов: 1360000 / 1485720
Обработано заказов: 1370000 / 1485720
Обработано заказов: 1380000 / 1485720
Обработано заказов: 1390000 / 1485720
Обработано заказов: 1400000 / 1485720
Обработано заказов: 1410000 / 1485720
Обработано заказов: 1420000 / 1485720
Обработано заказов: 1430000 / 1485720
Обработано заказов: 1440000 / 1485720
Обработано заказов: 1450000 / 1485720
Обработано заказов: 1460000 / 1485720
Обработано заказов: 1470000 / 1485720
Обработано заказов: 1480000 / 1485720
Обработано заказов: 1485720 / 1485720

In [3]:
# Обрабатываем каждый файл по очереди
for DATA_FILE in DATA_FILES:
    print(f"\nОбработка файла: {DATA_FILE}")

    # 1. Получаем уникальные заказы в этом файле
    order_ids = pl.read_csv(DATA_FILE, columns=["orderid"]).unique()
    # order_ids = pl.read_csv(DATA_FILE, separator=",", encoding="iso8859-1", columns=["orderid"]).unique()
    file_total_orders = order_ids.height
    total_orders += file_total_orders  # добавим к общему счётчику

    # 2. Читаем чанками по заказам
    for i in range(0, file_total_orders, BATCH_SIZE):
        batch_ids = order_ids.slice(i, BATCH_SIZE)

        batch_df = (
            pl.read_csv(DATA_FILE, columns=["orderid", "productid"])
            .join(batch_ids, on="orderid", how="inner")
            .group_by("orderid")
            .agg(pl.col("productid").unique().alias("products"))
        )

        for row in batch_df.iter_rows(named=True):
            products = sorted(set(row["products"]))
            item_counter.update(products)
            pairs = itertools.combinations(products, 2)
            pair_counter.update(pairs)

        print(f"  → Обработано заказов: {min(i + BATCH_SIZE, file_total_orders)} / {file_total_orders}")

Обработка файла: ../data/2024-20250000_part_00-003.csv
  → Обработано заказов: 10000 / 1482842
  → Обработано заказов: 20000 / 1482842
  → Обработано заказов: 30000 / 1482842
  → Обработано заказов: 40000 / 1482842
  → Обработано заказов: 50000 / 1482842
  → Обработано заказов: 60000 / 1482842
  → Обработано заказов: 70000 / 1482842
  → Обработано заказов: 80000 / 1482842
  → Обработано заказов: 90000 / 1482842
  → Обработано заказов: 100000 / 1482842
  → Обработано заказов: 110000 / 1482842
  → Обработано заказов: 120000 / 1482842
  → Обработано заказов: 130000 / 1482842
  → Обработано заказов: 140000 / 1482842
  → Обработано заказов: 150000 / 1482842
  → Обработано заказов: 160000 / 1482842
  → Обработано заказов: 170000 / 1482842
  → Обработано заказов: 180000 / 1482842
  → Обработано заказов: 190000 / 1482842
  → Обработано заказов: 200000 / 1482842
  → Обработано заказов: 210000 / 1482842
  → Обработано заказов: 220000 / 1482842
  → Обработано заказов: 230000 / 1482842
  → Обработано заказов: 240000 / 1482842
  → Обработано заказов: 250000 / 1482842
  → Обработано заказов: 260000 / 1482842
  → Обработано заказов: 270000 / 1482842
  → Обработано заказов: 280000 / 1482842
  → Обработано заказов: 290000 / 1482842
  → Обработано заказов: 300000 / 1482842
  → Обработано заказов: 310000 / 1482842
  → Обработано заказов: 320000 / 1482842
  → Обработано заказов: 330000 / 1482842
  → Обработано заказов: 340000 / 1482842
  → Обработано заказов: 350000 / 1482842
  → Обработано заказов: 360000 / 1482842
  → Обработано заказов: 370000 / 1482842
  → Обработано заказов: 380000 / 1482842
  → Обработано заказов: 390000 / 1482842
  → Обработано заказов: 400000 / 1482842
  → Обработано заказов: 410000 / 1482842
  → Обработано заказов: 420000 / 1482842
  → Обработано заказов: 430000 / 1482842
  → Обработано заказов: 440000 / 1482842
  → Обработано заказов: 450000 / 1482842
  → Обработано заказов: 460000 / 1482842
  → Обработано заказов: 470000 / 1482842
  → Обработано заказов: 480000 / 1482842
  → Обработано заказов: 490000 / 1482842
  → Обработано заказов: 500000 / 1482842
  → Обработано заказов: 510000 / 1482842
  → Обработано заказов: 520000 / 1482842
  → Обработано заказов: 530000 / 1482842
  → Обработано заказов: 540000 / 1482842
  → Обработано заказов: 550000 / 1482842
  → Обработано заказов: 560000 / 1482842
  → Обработано заказов: 570000 / 1482842
  → Обработано заказов: 580000 / 1482842
  → Обработано заказов: 590000 / 1482842
  → Обработано заказов: 600000 / 1482842
  → Обработано заказов: 610000 / 1482842
  → Обработано заказов: 620000 / 1482842
  → Обработано заказов: 630000 / 1482842
  → Обработано заказов: 640000 / 1482842
  → Обработано заказов: 650000 / 1482842
  → Обработано заказов: 660000 / 1482842
  → Обработано заказов: 670000 / 1482842
  → Обработано заказов: 680000 / 1482842
  → Обработано заказов: 690000 / 1482842
  → Обработано заказов: 700000 / 1482842
  → Обработано заказов: 710000 / 1482842
  → Обработано заказов: 720000 / 1482842
  → Обработано заказов: 730000 / 1482842
  → Обработано заказов: 740000 / 1482842
  → Обработано заказов: 750000 / 1482842
  → Обработано заказов: 760000 / 1482842
  → Обработано заказов: 770000 / 1482842
  → Обработано заказов: 780000 / 1482842
  → Обработано заказов: 790000 / 1482842
  → Обработано заказов: 800000 / 1482842
  → Обработано заказов: 810000 / 1482842
  → Обработано заказов: 820000 / 1482842
  → Обработано заказов: 830000 / 1482842
  → Обработано заказов: 840000 / 1482842
  → Обработано заказов: 850000 / 1482842
  → Обработано заказов: 860000 / 1482842
  → Обработано заказов: 870000 / 1482842
  → Обработано заказов: 880000 / 1482842
  → Обработано заказов: 890000 / 1482842
  → Обработано заказов: 900000 / 1482842
  → Обработано заказов: 910000 / 1482842
  → Обработано заказов: 920000 / 1482842
  → Обработано заказов: 930000 / 1482842
  → Обработано заказов: 940000 / 1482842
  → Обработано заказов: 950000 / 1482842
  → Обработано заказов: 960000 / 1482842
  → Обработано заказов: 970000 / 1482842
  → Обработано заказов: 980000 / 1482842
  → Обработано заказов: 990000 / 1482842
  → Обработано заказов: 1000000 / 1482842
  → Обработано заказов: 1010000 / 1482842
  → Обработано заказов: 1020000 / 1482842
  → Обработано заказов: 1030000 / 1482842
  → Обработано заказов: 1040000 / 1482842
  → Обработано заказов: 1050000 / 1482842
  → Обработано заказов: 1060000 / 1482842
  → Обработано заказов: 1070000 / 1482842
  → Обработано заказов: 1080000 / 1482842
  → Обработано заказов: 1090000 / 1482842
  → Обработано заказов: 1100000 / 1482842
  → Обработано заказов: 1110000 / 1482842
  → Обработано заказов: 1120000 / 1482842
  → Обработано заказов: 1130000 / 1482842
  → Обработано заказов: 1140000 / 1482842
  → Обработано заказов: 1150000 / 1482842
  → Обработано заказов: 1160000 / 1482842
  → Обработано заказов: 1170000 / 1482842
  → Обработано заказов: 1180000 / 1482842
  → Обработано заказов: 1190000 / 1482842
  → Обработано заказов: 1200000 / 1482842
  → Обработано заказов: 1210000 / 1482842
  → Обработано заказов: 1220000 / 1482842
  → Обработано заказов: 1230000 / 1482842
  → Обработано заказов: 1240000 / 1482842
  → Обработано заказов: 1250000 / 1482842
  → Обработано заказов: 1260000 / 1482842
  → Обработано заказов: 1270000 / 1482842
  → Обработано заказов: 1280000 / 1482842
  → Обработано заказов: 1290000 / 1482842
  → Обработано заказов: 1300000 / 1482842
  → Обработано заказов: 1310000 / 1482842
  → Обработано заказов: 1320000 / 1482842
  → Обработано заказов: 1330000 / 1482842
  → Обработано заказов: 1340000 / 1482842
  → Обработано заказов: 1350000 / 1482842
  → Обработано заказов: 1360000 / 1482842
  → Обработано заказов: 1370000 / 1482842
  → Обработано заказов: 1380000 / 1482842
  → Обработано заказов: 1390000 / 1482842
  → Обработано заказов: 1400000 / 1482842
  → Обработано заказов: 1410000 / 1482842
  → Обработано заказов: 1420000 / 1482842
  → Обработано заказов: 1430000 / 1482842
  → Обработано заказов: 1440000 / 1482842
  → Обработано заказов: 1450000 / 1482842
  → Обработано заказов: 1460000 / 1482842
  → Обработано заказов: 1470000 / 1482842
  → Обработано заказов: 1480000 / 1482842
  → Обработано заказов: 1482842 / 1482842

Обработка файла: ../data/2022-20230001_part_00-004.csv

ComputeError: could not parse `6031671536.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 13889823 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031671536.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```

In [28]:
# 3. Создаем итоговую таблицу правил
rules = []

for (item_A, item_B), pair_count in pair_counter.items():
    if item_A == item_B:
        continue  # пропускаем пару одинаковых товаров
    count_A = item_counter[item_A]
    count_B = item_counter[item_B]
    support = pair_count / total_orders
    confidence = pair_count / count_A if count_A else 0
    lift = (pair_count * total_orders) / (count_A * count_B) if (count_A and count_B) else 0


    rules.append({
        "item_A": item_A,
        "item_B": item_B,
        "pair_count": pair_count,
        "support": support,
        "confidence": confidence,
        "lift": lift
    })

In [29]:
# 4. Сохраняем все правила локально
rules_df = pl.DataFrame(rules)
os.makedirs("../results", exist_ok=True)
rules_df.write_parquet("../results/full_rules.parquet")

In [30]:
# 5. Топ-правила (по lift > 1.5)
top_rules = rules_df.filter(pl.col("lift") > 1.5).sort("lift", descending=True).head(100)
top_rules.write_csv("../results/top_rules.csv")

In [15]:
# 6. (Опционально) Сохраняем топ-правила в MongoDB
try:
    from pymongo import MongoClient
    MONGO_URI = "mongodb+srv://dianakhutorna_db_user:1MkZZDOie0bztsUk@yom.adk31s4.mongodb.net/?appName=YOM"
    client = MongoClient(MONGO_URI)
    db = client["mydatabase"]
    collection = db["results"]


    collection.delete_many({})
    collection.insert_many(top_rules.to_dicts())
    print("Топ-правила сохранены в MongoDB")
except Exception as e:
    print("MongoDB пропущена:", e)


print("Завершено: всё сохранено локально в /results")

Топ-правила сохранены в MongoDB
Завершено: всё сохранено локально в /results

In [21]:
# Загружаем продукты
products = pl.read_csv("../data/products_v2.csv", separator=";")
products.head()

shape: (5, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ productid ┆ name      ┆ category ┆ subcatego ┆ … ┆ amountper ┆ salesunit ┆ descripti ┆ categoric │
│ ---       ┆ ---       ┆ ---      ┆ ry        ┆   ┆ box       ┆ ---       ┆ on        ┆ allevel1  │
│ str       ┆ str       ┆ str      ┆ ---       ┆   ┆ ---       ┆ str       ┆ ---       ┆ ---       │
│           ┆           ┆          ┆ str       ┆   ┆ i64       ┆           ┆ str       ┆ str       │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 002942-00 ┆ MERMELADA ┆ 13       ┆ 1301      ┆ … ┆ 1         ┆ UND       ┆ MERMELADA ┆ Mermelada │
│ 8         ┆ FRAMBUESA ┆          ┆           ┆   ┆           ┆           ┆ FRAMBUESA ┆ s         │
│ 002943-00 ┆ MERMELADA ┆ 13       ┆ 1301      ┆ … ┆ 1         ┆ UND       ┆ MERMELADA ┆ Mermelada │
│ 3         ┆ PINA 5 kg ┆          ┆           ┆   ┆           ┆           ┆ PINA 5 KG ┆ s         │
│ 002944-00 ┆ MERMELADA ┆ 13       ┆ 1301      ┆ … ┆ 1         ┆ UND       ┆ MERMELADA ┆ Mermelada │
│ 4         ┆ DAMASCO   ┆          ┆           ┆   ┆           ┆           ┆ DAMASCO   ┆ s         │
│ 000083-00 ┆ LECHE     ┆ 15       ┆ 1502      ┆ … ┆ 1         ┆ KG        ┆ LECHE     ┆ S.N.S     │
│ 1         ┆ PURITA    ┆          ┆           ┆   ┆           ┆           ┆ PURITA    ┆           │
│           ┆ FORT. S   ┆          ┆           ┆   ┆           ┆           ┆ FORT. S   ┆           │
│ 000092-00 ┆ PURITA    ┆ 15       ┆ 1501      ┆ … ┆ 1         ┆ UND       ┆ PURITA    ┆ S.N.S     │
│ 1         ┆ CEREAL    ┆          ┆           ┆   ┆           ┆           ┆ CEREAL    ┆           │
│           ┆ PROLES    ┆          ┆           ┆   ┆           ┆           ┆ PROLES    ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [22]:
# Готовим словарь: productid → name
name_map = products.select(["productid", "name"])

In [33]:
# Загружаем правила
rules = pl.read_csv("../results/top_rules.csv")  # или твой путь

In [34]:
# Присоединяем названия по item_A
rules_named = (
    rules.join(name_map.rename({"productid": "item_A", "name": "name_A"}), on="item_A", how="left")
         .join(name_map.rename({"productid": "item_B", "name": "name_B"}), on="item_B", how="left")
)

In [35]:
# Сохраняем расширенный файл
rules_named.write_csv("../results/top_rules_named.csv")

In [36]:
# Пример вывода
rules_named.select(["item_A", "name_A", "item_B", "name_B", "lift"]).sort("lift", descending=True).head(10)

shape: (10, 5)
┌────────────────────┬────────────────────┬────────────────────┬────────────────────┬──────────────┐
│ item_A             ┆ name_A             ┆ item_B             ┆ name_B             ┆ lift         │
│ ---                ┆ ---                ┆ ---                ┆ ---                ┆ ---          │
│ str                ┆ str                ┆ str                ┆ str                ┆ f64          │
╞════════════════════╪════════════════════╪════════════════════╪════════════════════╪══════════════╡
│ 000300-003         ┆ SOPROLE YOG BATIDO ┆ 000401-009         ┆ MANJARATE Postre   ┆ 1.48572e6    │
│                    ┆                    ┆                    ┆ Ban                ┆              │
│ 000928-009         ┆ SOPROLE LECHE      ┆ 000929-009         ┆ SOPROLE LECHE      ┆ 371430.0     │
│                    ┆ SABOR              ┆                    ┆ SABOR              ┆              │
│ 000951-002         ┆ SOPROLE LECHE      ┆ 000952-002         ┆ SOPROLE LECHE      ┆ 37143.0      │
│                    ┆ PROTEI             ┆                    ┆ PROTEI             ┆              │
│ 002080-002         ┆ SOPROLE Leche      ┆ 002080-030         ┆ SOPROLE Leche      ┆ 12569.790457 │
│                    ┆ Cultiv             ┆                    ┆ Cultiv             ┆              │
│ 002081-002         ┆ SOPROLE Leche      ┆ 002081-030         ┆ SOPROLE Leche      ┆ 11603.561387 │
│                    ┆ Cultiv             ┆                    ┆ Cultiv             ┆              │
│ 002156-001         ┆ CREMA PASTEURIZADA ┆ 002857-001         ┆ SOPROLE Leche      ┆ 8074.565217  │
│                    ┆ 4                  ┆                    ┆ Polvo              ┆              │
│ 000000000000142021 ┆ null               ┆ 000000000000142022 ┆ null               ┆ 7738.125     │
│ 002080-030         ┆ SOPROLE Leche      ┆ 002081-030         ┆ SOPROLE Leche      ┆ 7108.708134  │
│                    ┆ Cultiv             ┆                    ┆ Cultiv             ┆              │
│ 002080-030         ┆ SOPROLE Leche      ┆ 002081-002         ┆ SOPROLE Leche      ┆ 6771.59414   │
│                    ┆ Cultiv             ┆                    ┆ Cultiv             ┆              │
│ 002080-002         ┆ SOPROLE Leche      ┆ 002081-030         ┆ SOPROLE Leche      ┆ 6732.234494  │
│                    ┆ Cultiv             ┆                    ┆ Cultiv             ┆              │
└────────────────────┴────────────────────┴────────────────────┴────────────────────┴──────────────┘

## Data Cleaning: 2022-2023 csv-files

In [5]:
!pip install chardet
import chardet

def detect_encoding(filepath, num_bytes=100_000):
    """
    Определяет кодировку файла на основе первых num_bytes байт.
    """
    with open(filepath, "rb") as f:
        raw = f.read(num_bytes)
    result = chardet.detect(raw)
    return result["encoding"]

# Пример использования
file_path = "../data/2022-20230000_part_00-002.csv"
encoding = detect_encoding(file_path)
print(f"Кодировка файла: {encoding}")

Collecting chardet
  Downloading chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Downloading chardet-5.2.0-py3-none-any.whl (199 kB)
   ---------------------------------------- 0.0/199.4 kB ? eta -:--:--
   -- ------------------------------------- 10.2/199.4 kB ? eta -:--:--
   ------ -------------------------------- 30.7/199.4 kB 435.7 kB/s eta 0:00:01
   ---------------------------------------  194.6/199.4 kB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 199.4/199.4 kB 1.7 MB/s eta 0:00:00
Installing collected packages: chardet
Successfully installed chardet-5.2.0
Кодировка файла: ascii

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import os
from pathlib import Path

def clean_csv_safe(input_path, output_path, expected_columns=2, delimiter=","):
    """
    Построчная очистка CSV:
    - удаляет строки с неверным числом столбцов
    - перекодирует из ISO-8859-1 в UTF-8
    """
    with open(input_path, "r", encoding="ascii", errors="ignore") as f_in, \
         open(output_path, "w", encoding="utf-8") as f_out:
        
        for line in f_in:
            line_clean = line.strip()
            if not line_clean:
                continue
            if line_clean.count(delimiter) >= (expected_columns - 1):
                f_out.write(line_clean + "\n")

In [7]:
# Папка с оригинальными файлами
data_dir = Path("../data")

# Создаём подкаталог для очищенных файлов
cleaned_dir = data_dir / "cleaned"
cleaned_dir.mkdir(exist_ok=True)

# Обрабатываем все .csv файлы
for file in data_dir.glob("*.csv"):
    cleaned_path = cleaned_dir / f"cleaned_{file.name}"
    print(f"Cleaning {file.name} → {cleaned_path.name}")
    clean_csv_safe(input_path=file, output_path=cleaned_path)

Cleaning 2022-20230000_part_00-002.csv → cleaned_2022-20230000_part_00-002.csv
Cleaning 2022-20230001_part_00-004.csv → cleaned_2022-20230001_part_00-004.csv
Cleaning 2024-20250000_part_00-003.csv → cleaned_2024-20250000_part_00-003.csv
Cleaning 2024-20250001_part_00-001.csv → cleaned_2024-20250001_part_00-001.csv

## Working with cleaned data

In [11]:
import polars as pl
import itertools
from collections import Counter, defaultdict
import math
import os
import csv

In [9]:
# Путь к файлу CSV (относительно папки notebooks)
DATA_PATH = "../data/2024-20250001_part_00-001.csv"
BATCH_SIZE = 10_000

# Список путей ко всем CSV-файлам
DATA_FILES = [
    #"../data/2024-20250001_part_00-001.csv",
    #"../data/2024-20250000_part_00-003.csv",
    "../data/cleaned/cleaned_2022-20230000_part_00-002.csv",
    "../data/cleaned/cleaned_2022-20230001_part_00-004.csv"
]

import glob

# Получаем список всех CSV-файлов в папке ../data
# DATA_FILES = sorted(glob.glob("../data/*.csv"))

# Словарь для хранения количества каждой пары товаров
pair_counter = Counter()
item_counter = Counter()
total_orders = 0  # суммарно по всем файлам

In [10]:
# Обрабатываем каждый файл по очереди
for DATA_FILE in DATA_FILES:
    print(f"\nОбработка файла: {DATA_FILE}")

    # 1. Получаем уникальные заказы в этом файле
    order_ids = pl.read_csv(DATA_FILE, columns=["orderid"]).unique()
    # order_ids = pl.read_csv(DATA_FILE, separator=",", encoding="iso8859-1", columns=["orderid"]).unique()
    file_total_orders = order_ids.height
    total_orders += file_total_orders  # добавим к общему счётчику

    # 2. Читаем чанками по заказам
    for i in range(0, file_total_orders, BATCH_SIZE):
        batch_ids = order_ids.slice(i, BATCH_SIZE)

        batch_df = (
            pl.read_csv(DATA_FILE, columns=["orderid", "productid"])
            .join(batch_ids, on="orderid", how="inner")
            .group_by("orderid")
            .agg(pl.col("productid").unique().alias("products"))
        )

        for row in batch_df.iter_rows(named=True):
            products = sorted(set(row["products"]))
            item_counter.update(products)
            pairs = itertools.combinations(products, 2)
            pair_counter.update(pairs)

        print(f"  → Обработано заказов: {min(i + BATCH_SIZE, file_total_orders)} / {file_total_orders}")

Обработка файла: ../data/cleaned/cleaned_2022-20230000_part_00-002.csv

ComputeError: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```

In [12]:
# Устойчивый способ извлечения orderid
def extract_order_ids(csv_path, encoding="utf-8"):
    order_ids = set()
    with open(csv_path, "r", encoding=encoding, errors="ignore") as f:
        reader = csv.DictReader(f)
        for row in reader:
            oid = row.get("orderid")
            if oid:
                order_ids.add(oid)
    return list(order_ids)

In [13]:
# Обрабатываем каждый файл
for DATA_FILE in DATA_FILES:
    print(f"\nОбработка файла: {DATA_FILE}")

    order_id_list = extract_order_ids(DATA_FILE)
    order_ids = pl.DataFrame({"orderid": order_id_list})
    file_total_orders = len(order_id_list)
    total_orders += file_total_orders

    # Обработка чанками
    for i in range(0, file_total_orders, BATCH_SIZE):
        batch_ids = order_ids.slice(i, BATCH_SIZE)

        try:
            batch_df = (
                pl.read_csv(DATA_FILE, columns=["orderid", "productid"])
                .join(batch_ids, on="orderid", how="inner")
                .group_by("orderid")
                .agg(pl.col("productid").unique().alias("products"))
            )
        except Exception as e:
            print(f"⚠️ Ошибка при чтении чанка: {e}")
            continue

        for row in batch_df.iter_rows(named=True):
            products = sorted(set(row["products"]))
            item_counter.update(products)
            pairs = itertools.combinations(products, 2)
            pair_counter.update(pairs)

        print(f"  → Обработано заказов: {min(i + BATCH_SIZE, file_total_orders)} / {file_total_orders}")

Обработка файла: ../data/cleaned/cleaned_2022-20230000_part_00-002.csv
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `6031667185.0` to the `null_values` list.

Original error: ```remaining bytes non-empty```
⚠️ Ошибка при чтении чанка: could not parse `6031667185.0` as dtype `i64` at column 'orderid' (column number 1)

The current offset in the file is 15287986 bytes.

You might want to try:

KeyboardInterrupt: